import { FSAGraph, Node, Transition } from '../models';

/**
 * Represents the 'current state of the FSA' while processing an input.
 * A duplicate configuration would be a sign of an epsilon loop.
 */
export interface Configuration {
	state: Node;
	stack: string[]; // empty for non PDAs
	group: number;
}

/**
 * Node of a computation tree, which holds information about the configuration of the FSA at a that point of the computation. In order to navigate the tree, each node has a reference to its parent and to the transition taken to reach it from the parent, and of course its children.
 */
export class ComputationNode {
	config: Configuration;
	parent: ComputationNode | null;
	transitionTaken: Transition | null;
	children: ComputationNode[];

	constructor(
		{ state, stack, group }: Configuration,
		parent: ComputationNode | null = null,
		transitionTaken: Transition | null = null
	) {
		this.config = { state, stack, group };
		this.parent = parent;
		this.transitionTaken = transitionTaken;
		this.children = [];
	}

	/**
	 * Adds a child to the current node, with the given configuration and transition. It then returns the newly created child node.
	 * @param config The configuration of the child node to be added.
	 * @param viaTransition The transition taken from the current node to reach the child node.
	 * @returns The newly created child node.
	 */
	addChild(config: Configuration, viaTransition: Transition): ComputationNode {
		const newNode = new ComputationNode(config, this, viaTransition);
		this.children.push(newNode);
		return newNode;
	}

	isLeaf(): boolean {
		return this.children.length === 0;
	}

	/**
	 * Converts the subtree rooted at the current node into a string representation. Mostly there for easy debugging.
	 * @param indent The indentation to be used for the current node, based on its depth in the tree.
	 * @param isLast Whether the current node is the last child of its parent.
	 * @returns Pretty string representation of the subtree rooted at the current node.
	 */
	toString(indent: string = '', isLast: boolean = true): string {
		const prefix = indent + (isLast ? '└─ ' : '├─ ');
		const stackStr = `[${this.config.stack.join(',')}]`;
		const transitionStr = this.transitionTaken ? ` via '${this.transitionTaken.toString()}'` : '';
		let result = `${prefix}${this.config.state.label}${stackStr} (g${this.config.group})${transitionStr}\n`;
		const childIndent = indent + (isLast ? ' ' : '│ ');
		this.children.forEach((child, index) => {
			const isLastChild = index === this.children.length - 1;
			result += child.toString(childIndent, isLastChild);
		});
		return result;
	}
}

export type StepType = 'start' | 'consume-symbol' | 'epsilon-closure';

export interface ComputationStep {
	inputIndex: number;
	type: StepType;
	activeNodes: ComputationNode[];
}

/**
 * Tree generated by processing a given input on an FSA.
 * Each node in the tree represents a configuration of the FSA at a certain point in the computation, and are also organized in 'groups' based on how many symbols of the input have been processed to reach that configuration (this is helpful as the same group can be spread out across multiple levels, due to epsilon transitions).
 * For simplicity, a stack is used regardless of the FSA type, and it is simply empty (aka it can be ignored) for non PDAs.
 */
export class ComputationTree {
	readonly maxVisits: number;
	readonly root: ComputationNode;
	readonly steps: ComputationStep[] = [];
	readonly input: string[];
	private inputIndex: number;
	private fsa: FSAGraph;
	warnings: string[] = [];

	constructor(fsa: FSAGraph, input: string[], maxVisits: number = 0) {
		this.fsa = fsa;
		this.input = input;
		this.inputIndex = -1; // starting at -1 as the initial step will not consume any symbol
		this.maxVisits = maxVisits;
		if (this.fsa.startNode === null) {
			throw new Error('FSA is missing start node, cannot compute input.');
		}

		// Initialize the tree by creating the root node (using the start state in the FSA) and compute its epsilon closure.
		this.newStep(this.inputIndex, 'start');
		const root = new ComputationNode({
			state: this.fsa.startNode,
			stack: [],
			group: this.inputIndex
		});
		this.root = root;
		this.pushToCurrentStep(root);

		this.newStep(this.inputIndex, 'epsilon-closure');
		this.computeEpsilonClosure(
			root,
			new Map([[root.config.state.id, new Set([this.encodeStack(root.config.stack)])]])
		);

		// Process the input in a similar fashion: for each symbol, first 'move' to the next group (using transitions matching the symbol, if any), then compute the epsilon closure for the new group before moving on to the next symbol.
		this.input.forEach((symbol) => {
			let currentlyActiveNodes = this.currentStep.activeNodes;
			this.inputIndex++;
			this.newStep(this.inputIndex, 'consume-symbol');
			currentlyActiveNodes.forEach((node) => {
				this.computeSymbol(node, symbol);
			});

			currentlyActiveNodes = [...this.currentStep.activeNodes];
			this.newStep(this.inputIndex, 'epsilon-closure');
			currentlyActiveNodes.forEach((node) => {
				this.computeEpsilonClosure(
					node,
					new Map([[node.config.state.id, new Set([this.encodeStack(node.config.stack)])]])
				);
			});
		});
	}

	/**
	 * Gets all accepting paths in the computation tree. The criteria is:
	 * - the last node in the path must be in the very last group (aka after processing the entire input)
	 * - the state in said node must be accepting
	 * - the stack in said node must be empty
	 */
	get acceptingPaths(): ComputationNode[][] {
		const lastGroup = this.steps[this.steps.length - 1].activeNodes;
		const acceptingPathLeaves = lastGroup.filter(
			(node) => node.config.state.isAccepting && node.config.stack.length === 0
		);
		return acceptingPathLeaves.map((leaf) => this.getPathFromRoot(leaf));
	}

	private newStep(inputIndex: number, type: StepType) {
		this.steps.push({
			inputIndex,
			type,
			activeNodes: type === 'epsilon-closure' ? [...this.currentStep.activeNodes] : []
		});
	}

	private pushToCurrentStep(...nodes: ComputationNode[]) {
		this.currentStep.activeNodes.push(...nodes);
	}

	get currentStep(): ComputationStep {
		return this.steps[this.steps.length - 1];
	}

	/**
	 * Gets all valid transitions from a given state, based on the symbol to be consumed and the current stack top (if any).
	 * @param source The source state.
	 * @param consume The symbol to be consumed by the transition.
	 * @param stackTop The current stack top, if any. If not provided, stack operations are ignored.
	 * @returns The list of valid transitions (in the form of [transition, target state]) from the source state, matching the given criteria.
	 */
	private getValidTransitions(
		state: Node,
		consume: string,
		stackTop?: string
	): [Transition, Node][] {
		const transitions = this.fsa.adjacencyMap.get(state) ?? [];
		let validTransitions = transitions.filter(([t]) => t.consume === consume);
		if (stackTop != undefined) {
			validTransitions = validTransitions.filter(
				([t]) => t.pop === Transition.EPSILON || t.pop === stackTop
			);
		}
		return validTransitions;
	}

	/**
	 * Computes an input symbol for the given node. It adds reachable configurations as children of the given node, and adds them to the current group.
	 * @param node The node for which the symbol should be computed.
	 * @param symbol The consume symbol to be computed.
	 */
	private computeSymbol(node: ComputationNode, symbol: string) {
		const validTransitions = this.getValidTransitions(
			node.config.state,
			symbol,
			node.config.stack.at(-1)
		);
		validTransitions.forEach(([transition, targetState]) => {
			const adjustedStack = [...node.config.stack];
			if (this.fsa.hasStackOps) {
				if (transition.pop != Transition.EPSILON) adjustedStack.pop();
				if (transition.push != Transition.EPSILON) adjustedStack.push(transition.push!);
			}
			const config = {
				state: targetState,
				stack: adjustedStack,
				group: this.inputIndex
			};
			const newNode = node.addChild(config, transition);
			this.pushToCurrentStep(newNode);
		});
	}

	/**
	 * Computes the epsilon closure for the given node, by adding reachable configurations as children of the given node, and adding them to the current group. The epsilon closure is computed recursively until no new configuration is found, or until a possible infinite loop is detected.
	 * NOTE: an infinite loop should only be possible (the way this tree is implemented) in PDAs where there is an epsilon loop that keeps incrementing the stack infinitely. In any other scenario, the loop will eventually stop when we either encounter a previously seen configuration, or when we exhaust all possible transitions.
	 * @param node The node for which the epsilon closure should be computed.
	 * @param seenConfigs Set of configurations already seen in the current path of the recursion, used to detect loops.
	 * @param visitCounter Map that counts the number of visits to each state, used to detect possible infinite loops. Should be left empty when calling the function.
	 */
	private computeEpsilonClosure(
		node: ComputationNode,
		seenConfigs: Map<string, Set<string>> = new Map()
	) {
		const validTransitions = this.getValidTransitions(
			node.config.state,
			Transition.EPSILON,
			node.config.stack.at(-1)
		);

		for (const [transition, targetState] of validTransitions) {
			const adjustedStack = [...node.config.stack];
			if (this.fsa.hasStackOps) {
				if (transition.pop != Transition.EPSILON) adjustedStack.pop();
				if (transition.push != Transition.EPSILON) adjustedStack.push(transition.push!);
			}
			const config = {
				state: targetState,
				stack: adjustedStack,
				group: this.inputIndex
			};

			const previouslySeenStacks = seenConfigs.get(config.state.id) ?? new Set<string>();
			const currentStack = this.encodeStack(config.stack);
			if (previouslySeenStacks.has(currentStack)) {
				continue; // configuration already seen in the current path, no need to revisit
			}

			// here we use prefixes to check if we're in a loop were the stack is simply growing indefinitely. The logic is: if we already arrived at this state, and we have a number X of previously seen stacks that are prefixes of the current stack, then it means we're in iteration X of an infinite loop. If X is bigger than the maxVisits threshold, we stop exploring this branch and add a warning to the tree.
			const prefixCount = [...previouslySeenStacks].reduce((count, seenStack) => {
				return count + (currentStack.startsWith(seenStack) ? 1 : 0);
			}, 0);
			if (prefixCount > this.maxVisits) {
				this.warnings.push(
					`Possible infinite epsilon loop involving state '${node.config.state.label}' and transition '${node.transitionTaken?.toString()}'. Halted exploration of this branch after ${this.maxVisits} loops through it.`
				);
				continue;
			}

			seenConfigs.set(config.state.id, previouslySeenStacks.add(currentStack));
			const newNode = node.addChild(config, transition);
			this.pushToCurrentStep(newNode);
			this.computeEpsilonClosure(newNode, seenConfigs);
			// backtrack (resets) the visit counter and seen configs for the current node, in order to ONLY detect loops in the current path of the recursion, not in other branches.
			seenConfigs.get(config.state.id)?.delete(currentStack);
		}
	}

	/**
	 * Simple helper to convert a stack into a string representation, used for quick comparison of configurations and to detect loops.
	 * The traling comma is used as end-of-stack marker, to avoid issues where ['A', 'B'] could be interpreted as a prefix to ['A','BB'], as they would be converted to 'A,B' and 'A,BB'. With the trailing comma, they become 'A,B,' and 'A,BB,' which remove that ambiguity when comparing stack configurations as strings.
	 * @param config The configuration for which the stack should be converted into a string.
	 * @returns The string representation of the stack in the given configuration.
	 */
	private encodeStack(stack: string[]): string {
		return stack.length > 0 ? `${stack.join(',')},` : '';
	}

	/**
	 * Given a node in the computation tree, it returns the path from the root to that node as a list of nodes. The path is ordered from the root (first element) to the given node (last element).
	 * @param node The node for which the path from the root should be computed.
	 * @returns The complete path from the root to the given node.
	 */
	getPathFromRoot(node: ComputationNode): ComputationNode[] {
		const path: ComputationNode[] = [];
		let currentNode: ComputationNode | null = node;
		while (currentNode) {
			path.unshift(currentNode);
			currentNode = currentNode.parent;
		}
		return path;
	}

	/**
	 * Helper to get all the groups in the computation tree as a string, used for debugging.
	 * @returns All the groups in the computation and their content tree as a string.
	 */
	getGroupsAsString(): string {
		const groups = new Map<number, Set<ComputationNode>>();
		this.steps.forEach((step) => {
			if (!groups.has(step.inputIndex)) {
				groups.set(step.inputIndex, new Set<ComputationNode>());
			}
			step.activeNodes.forEach((node) => groups.get(step.inputIndex)?.add(node));
		});
		let result = 'Groups:\n';
		groups.forEach((nodes, i) => {
			result += `${i}. [`;
			result += [...nodes]
				.map((node) => `${node.config.state.label}[${node.config.stack.join(',')}]`)
				.join(', ');
			result += ' ]\n';
		});
		return result;
	}

	/**
	 * Helper to get all the accepting paths in the computation tree as a string, used for debugging.
	 * @returns All the accepting paths in the computation tree as a string, or a simple message if no accepting path is found.
	 */
	getAcceptingPathsAsString(): string {
		const paths = this.acceptingPaths;
		if (paths.length === 0) {
			return 'No accepting paths found.\n';
		}
		let result = `Accepting path(s):\n`;
		paths.forEach((path, index) => {
			result += `Path ${index + 1}: ${path
				.map((node) => `${node.config.state.label}[${node.config.stack.join(',')}]`)
				.join(' -> ')}\n`;
		});
		return result;
	}

	/**
	 * Helper to get the tree (as in only the parent-child relationships between configurations, without the groups and other data) as a string, used for debugging.
	 * @returns The tree structure of the computation tree as a string.
	 */
	getComputationTreeAsString(): string {
		let result = 'Tree:\n';
		result += this.root.toString();
		return result;
	}

	/**
	 * Converts the entire computation tree (including groups and other data, not just the tree itself) into a readable, pretty string representation, used for debugging.
	 * @returns The entire computation tree as a string, including the groups and the accepting paths.
	 */
	toString(): string {
		let result = `Computation tree for input: '${this.input.join(',')}'\n`;
		if (this.warnings.length > 0) {
			result += 'Warnings:\n';
			this.warnings.forEach((w) => (result += `- ${w}\n`));
		}
		result += this.getGroupsAsString();
		result += this.getAcceptingPathsAsString();
		result += this.getComputationTreeAsString();
		return result;
	}
}
